---
title: The problem and promise of scale in multilayer networks
output: 
  github_document:
    toc: true
author: Alec Robitaille, Quinn M.R. Webber, Julie Turner and Eric Vander Wal
date: "-- `r Sys.Date()`"
---

Scale remains a seminal concept in ecology. Spatial scale has become a central consideration in the way we understand landscape ecology and animal space use. Multilayer networks promise the integration of monolayer animal social networks with the complexity and importance of animal movement and space use in heterogenous landscapes. Despite the complex interplay between social networks and how animals use space, there remains an important biological and methodological gap in our understanding of how an animals perception of spatial scale, e.g., grain and extent, can affect multilayer network dynamics. Here, we test how multilayer network metrics (e.g., versatility, multi-degree, similarity) are sensitive to variation in an animals perception of scale. We will simulate animal movement data coupled with emergent social networks on increasingly heterogenous landscapes across spatial scales. Furthermore, we review specific examples of spatially explicit data types to include in multilayer networks and explore the relevant nuances of these data. Our simulations will highlight the need to carefully select scales for measuring spatial processes and appropriately weight layers and edges representing different types of data. Effective integration of spatial processes, including biologically meaningful scales, within the context of animal social networks is an emerging area of research; our contribution will uniquely incorporate landscape ecology theory as a way to link different scales of social and spatial processes in a multilayer network. Based on social network and landscape ecology theory as well as our simulations we demonstrate potential for interconnectedness among individual animals and the landscapes they occupy.
