---
output: 
  github_document:
    toc: true
author: Alec Robitaille, Quinn M.R. Webber, Julie Turner and Eric Vander Wal
date: "-- `r Sys.Date()`"
bibliography: ../references/refs.bib
---



# Box 1: Types of spatial variables 
<!-- try:

I think you could organize this in the analytical steps you will follow and then have the effect of scale at the end of each? Then you can demonstrate the additive effects scale decisions can have

 Biologging data and landscape data
- table
Multilayer networks: Edges
- images
 Combining networks and spatial data
- information about your results
--> 


Multilayer networks can incorporate spatial variables to define edges between nodes and to characterize the spatial context of network layers. Edges connect different entities in the same layer or across layers, or the same entities across layers. The spatial context of a network layer is defined here as the landscape elements, generally abiotic, that an animal social system exists within. A multilayer network may include one or both types of spatial variables to better understand the complex connections between individuals and the landscapes they occupy.  


The main types of spatial data that are included in multilayer networks are georeferenced biologging data and landscape level data. Georeferenced biologging data, including radio-frequency identification tags (RFID), passive
integrated transponder (PIT), radiotelemetry, and Global Positioning System (GPS) devices, provide an alternative to intensive direct observations of individuals and their interactions. Also, many animals are small or cryptic, e.g.: marine mammals and birds, thus remotely sensed data are used to infer behavioural processes. Many derived products can be generated from these data as well, including home ranges, utilization distributions and habitat patches. Landscape scale data include relatively static measures of a lanscape such as land cover, land use, and elevation, and more dynamic measures such as temperature, precipitation and snow cover. 


Given the variety of multilayer networks and types of spatial data that can be included, there are many ways to integrate spatial data within multilayer networks. For example, multilayer networks may be composed of categorical and unordered layers (termed 'categorical coupling') defined by spatial variables such as land cover, land use, and explicit habitat patches. Multiplex networks, where each layer represents a different type of interaction, may be composed of layers defined by association indices and by home range overlap. Finally, a network of networks may be used to represent *communities* as layers with interlayer edges defined by their spatial connectivity and intralayer edges defined by a spatially derived association index. 

<!-- it's complicated -->

<!-- the list of accuracies could be a table -->
Spatial scale influences the inferences derived from spatial data when combining them in a multilayer network. All biologging sensors have some limiting spatial resolution: PIT tags have <1m reading distance [@krause2013], radio telemetry can have >10m location error, and GPS devices are accurate within 3-30m, largely influenced by habitat and vegetation cover. Also, biologging sensors vary in terms of data collection rate with GPS devices recording spatial locations on fixed measurement rates, PIT tags only recording spatial locations when individuals are within the reading distance of a fixed recording device and radio telemetry requiring either active users with handheld receivers or fixed receivers at specific locations. All landscape level measures derived from remotely sensed imagery are defined by their spatial resolution. Typically ranging from 1-1000m, the spatial resolution of an image is the length of one side of a pixel, usually square, that corresponds to its relative size on the ground. In conclusion, combining the scale of the imagery and the fix rate of biologging devices *can be resolved using <reccomendation>*.

---



* how associations are measured: e.g. spatsoc
* how relocations are categorized: e.g. landcover

Multilayer networks incoroprate spatial variables in two ways:

1. for determining association between individuals in a social system
1. for characterizing the spatial context of social systems


## Measuring association
For example, association between individuals can be determined using georeferenced biologging devices such as radio‐frequency identification tags, radiotelemetry, and global positioning system (GPS) devices. 

Proximity based social networks (PBSNs) are association networks based on close proximity between individuals [@spiegel2016]. 

Biologging with GPS allows for simultaneous spatiotemporal sampling of multiple individuals in a group or population 




## Spatial context
The spatial context of social systems can be defined as all

what is the spatial context of an animal social system

explicit spatial locations
habitat patches
landscape/habitat connectivity
social variable + home range overlap = opportunity to interact



# References

