---
output: 
  word_document:
    reference_docx: template.docx
  # github_document
author: Alec Robitaille, Quinn M.R. Webber, Julie Turner and Eric Vander Wal
date: "`r Sys.Date()`"
bibliography: ../references/refs.bib
csl: vancouver.csl
---

## Glossary

**Connective redundancy**: 1 - (neighborhood / degree) When connective redundancy is 0, all edges on all layers are necessary to preserve the social ties.[QW: FROM ALEC'S WRITING IN THE MS]

**Degree centrality**:

**Degree deviation**:

**Interlayer edge**: 

**Intralayer edge**:

**Monolayer**:

**Multidegree**: 

**Neighbours**: degree within a network layer.[QW: FROM ALEC'S WRITING IN THE MS]

**Relevance**: neighborhood of specific layer  / neighbourhood of full ml net. This is the proportion of neighbors present on the layer of focus. Comparing across, it tells you which layers are most important for each individual. [QW: FROM ALEC'S WRITING IN THE MS]

**Social environment**: Social life of an individual (or group of individuals) described by social interactions (Saltz et al. 2016).

**Social scale**: The type of social relationship observed that can be explicitly defined and measured in social network analyses (Farine 2015). For example, social interactions where animals come in direct contact (e.g. grooming) constitute the finest social scale, while co-occurrence or social association constitute an intermediate social scale, and home range overlap constitutes a coarse social scale.

**Spatial network**: Networks of locations, which be linked with social networks of animals that move between the locations (Silk et al. 2018).



<!--
## Each metric's interpretation
* Degree: the number of direct connections an individual has to other individuals in the network. High degree = connected to many indviduals in a single layer. Low degree = not connected to many individuals in a single layer.

* Multidegree: sum of degree across layers. High multidegree = connected to many
individuals across layers. Low multidegree = not connected to many individuals
across layers.

* Degree deviation: standard **[??]** deviation of degree across layers. High degree deviation =
large difference between degree for an individual across layers. Low degree
deviation = individuals are similarly connected across layers.

* Graph strength: the sum of all the edge weights directly connected to an actor, sometimes called weigthed degree. High graph strength = highly social, connected to many individuals and/or having stronger, high-valued connections between individuals. Low graph strength = not very social, connected to few individuals and/or having weak, low-valued connections between individuals. Not summed in this case across layers.

* Neighbours: number of unique individuals adjacent to each actor. Considered in
a single layer, this is equal to the degree.

* Neighbourhood: number of unique individuals across all layers. High
neighbourhood = a high number of unique individuals connected to an actor. Low
neighbourhood = a low number of unique individuals connected to an actor. 

* Relevance: layer centric metric, corresponding to the number of neighbours on a
layer divided by the total neighbourhood for each actor. High relevance = the layer is highly relevant to the individuals connections. A low
relevance means this layer does not contribute many neighbours to an individuals
overall neighbourhood.

* Connective redundancy: the total multilayer neighbourhood divided by the
multidegree. High connective redundancy indicates a multilayer network that has
many repeated edges across layers between an actor and its neighbours. Low
connective redundancy indicates that each layer is important for preserving all
social ties.

* Layer similarity: how similar each layer is (Brodka 2018). Pearson's
correlation coefficient of degree vectors for each layer, comparing each
landcover across seasons.


-->

# References
