---
output: github_document
bibliography: ../references/refs.bib
csl: cite.csl
---

# Introduction

<!-- ### Landscape spatial scale -->
Our understandings of ecological pattern and process are directly linked to the scale at which they are observed [@levin1992problem; @allen2015]. Animals and landscapes are influenced across scales by higher level processes, such as climate and productivity [@field2009], and lower level processes, such as species interactions and resource availability [@legendre1993; @chave2013]. The effect of scale has been explicity considered in ecology including in species distribution [@elith2009], habitat selection [@mayor2007] and food webs [@sugihara1989b]. Scale can be considered for all measured quantities [@schneider2009] including spatial and temporal variables as well as domain specific variables such as sociality.


<!-- observational scales of landscapes do not necessarily correspond to the "scale of effect" of species-landscape relationships, or the scale at which there is the strongest relationship [@jackson2015]-->

<!-- the scales that influence animals and the patterns of their landscapes may be disjoint [@chave2013].  -->

<!-- observers bias their perspective when selecting a scale,often unknowingly or without considering the implications [@allen2015].  -->

<!-- Spatial scale is a central consideration in the way we understand landscape ecology and animal space use.  -->



<!-- ### Social proximity scale  -->
Sociality, defined simply as the degree of shared space use among conspecifics [@tinbergen1951], exists across scales. For example, grooming and mating relationships requires close proximity between conspecifics and occurs over brief time periods whereas home range overlap occurs over larger spatial and temporal scales. Shared space is a requirement for social interaction, however, it remains unclear whether spatial proximity scales predictably with social interactions [@castles2014a; @farine2015a]. Social scale can be defined as the type of relationship observed [@farine2015a] and these relationships can be explicitly defined and measured in social network analyses [@farine2015b]. 


<!-- ### Regular networks
* SNA significant outcomes
-->

Rooted in mathematical graph theory, animal social networks measure the relationships of individuals and organization of social systems [@krause2009; @wey2008a; @croft2008]. Social network analyses provide insight into mating behaviours, interspecific interactions, and community structures [@pinter-wollman2014]. 
The structure of social networks influences population dynamics and evolutionary processes [@kurvers2014]. Nevertheless, social network analyses usually only consider a single measure of sociality, drastically simplifying the complexity of animal social systems [@finn2019]. 


<!-- Network theory and social network analysis allows one to scale across dyads, groups, etc from pairwise interactions to social units, networks etc[@krause2009] -->

<!-- infer process from large scale pattern [@krause2009] -->







<!-- ### Multilayer networks
used across disciplines
-->
Multilayer networks explicitly consider social systems across temporal, spatial and social contexts [@pilosof2017a]. They are made up of multiple layers, each representing relationships, individuals, spatial areas or temporal windows [@kivela2014; @porter2018a]. <!--GENERALLY INTERESTING Recently used in animal behaviour studies, multilayer networks have the potential to better characterize complex social systems [@silk2018a; @finn2019].-->


For multilayer social networks, three types of scale are relevant: spatial, temporal and social scale.

<!-- ### Case study 
deer
fogo caribou
-->
We will use two case studies to explore the sensitivity of multilayer network measures across scales. One, using an island population of caribou (*Rangifer tarandus*)



integrating networks across scales
explore sensitivity of network measures to scale



Despite the interplay between social networks and how animals use space, there remains an important biological and methodological gap in our understanding of how an animals perception of spatial scale, e.g., grain and extent, 

We will simulate animal movement data coupled with emergent social networks on increasingly heterogenous landscapes across spatial scales. 


---




Furthermore, we review specific examples of spatially explicit data types to include in multilayer networks and explore the relevant nuances of these data. Our simulations will highlight the need to carefully select scales for measuring spatial processes and appropriately weight layers and edges representing different types of data. Effective integration of spatial processes, including biologically meaningful scales, into animal social networks is an emerging area of research. Our contribution will incorporate landscape ecology theory as a way to link different scales of social and spatial processes in a multilayer network. Based on social network and landscape ecology theory as well as our simulations we demonstrate potential for interconnectedness among individual animals and the landscapes they occupy.



---





potential for interconnectedness among individual animals and the landscapes they occupy.


Animal social systems are complex and multifaceted

traditionally, animal social systems are measured using direct observation, telemetry or pit tags
interactions, e.g. grooming, aggression, etc,  between individuals are quantified by simplified measures 
and often lacking any indication of the spatial context of the interaction

recently the multilayer has been used to 

along with spatial variables, comes a large history of landscape ecology exploring and evaluating sensitivity to scale


here we'll use simulations to evaluate the impact of scale on social and spatial variables 
to better understand it's impact, implications in ML networks





# Multilayer Networks
Multilayer networks combine network layers with interlayer edges

Two main types of multilayer networks exist: multiplex networks and interconnected networks. Layers in multiplex networks consist of the same entities with each layer representing either a different type of interaction (as in multirelational networks) or a different time point or window (as in temporal networks). Layers in interconnected networks consist of the same or different entities with layers representing different subsystems (as in networks of networks), different types of entities (as in intercontextual networks), or different spatial locations (as in spatial networks) [@finn2019]. 

Of these, we have identified multirelational networks, networks of networks, intercontextual networks and spatial networks as likely to have spatial and scale considerations


Layers in multilayer networks can be
Animal social systems are 

What is a network

How does a ML network build on that

Which can include spatial variables


Multifaceted nature of animal social systems 
many variables having a spatial component
including landcover and habitat type
fix rate and 

spatial variables defined by 





# Scale
perception of scale




What is scale

in LE lit, how has scale been investigated

Elements of scale relevant to animal social systems, animal movement data, landcover data

Grain is this, extent is this

How might scale influence results

What kinds of spatial scale are there




# References

