---
output: 
  github_document:
    toc: true
author: Alec Robitaille, Quinn M.R. Webber, Julie Turner and Eric Vander Wal
date: "-- `r Sys.Date()`"
---

We determined three types of multilayer networks most relevant to spatial variables. Multilayer networks with layers defined by spatially explicit locations, interspecific interactions, and community or subpopulation structure. 
Other types of networks, such as intercontexual networks or temporal networks, are likely only to incorporate spatial variables in a hybrid multilayer network and considerations for including those variables will be explored here 


### Table 1

In table 1, we define three types of multilayer networks that incorporate spatial variables. 
How are layers defined, nodes defined, inter layer edges

We list variables affected by spatial and social scale

We use a definition of spatial scale from LE, 

social scale is 

TODO: find pictures of ML nets to include




|               | Spatial                                                           | Net of nets                                      | Interspecific                                              |
|---------------|-------------------------------------------------------------------|--------------------------------------------------|------------------------------------------------------------|
| layer         | spatially explicit                                                | subpops, fuzzy patches                           | dif species                                                |
| node          | individuals                                                       | ind + nets                                       | ind + species nets                                         |
| inter edges   | to self                                                           | to nets                                          | to species                                                 |
| intra edges   | association to other                                              | association                                      | association                                                |
| social grain  | type of interaction, chain rule, spatsoc threshold, hyena session | for intra, see left. for inter: define community |  for intra, see left. for inter: similarity, vulnerability |
| spatial grain | resolution                                                        | patches, k=                                      | connectivity, clusters                                     |

