---
output: 
  github_document:
    toc: true
author: Alec Robitaille, Quinn M.R. Webber, Julie Turner and Eric Vander Wal
date: "-- `r Sys.Date()`"
---

#### From issue organisers

* Appreciate ambition to link LE and SNA.
* Like the idea of reviewing different kinds of spatial data relevant to ML framework
* Hope simulations will be as relevant to movement and SNA data typically collected
* Manuscript will be relevant to both theoreticians and empiricists

**Conservation implications**



## Plan
Verbal model -> simulation, control for specific variables, expectations -> small real data

## To add

### Introduction?
We determined three types of multilayer networks most relevant to spatial variables. Multilayer networks with layers defined by spatially explicit locations, interspecific interactions, and community or subpopulation structure. 
Other types of networks, such as intercontexual networks or temporal networks, are likely only to incorporate spatial variables in a hybrid multilayer network and considerations for including those variables will be explored here 


## Simulations
selection coefficient, strength of selection, grain, movement, step length, turn angle


circuitscape


## Keywords

1. spatial scale
1. social systems
1. multilayer networks
1. landscape ecology
1. network theory


## Skeleton
* Abstract
* Brief introduction
  * Networks, social networks, animal social systems 
  * Landscape ecology, scale
* Multilayer Networks
  * What is a ML network
  * What kinds of ML nets exist
  * Which are relevant to spatial variables
* Scale 
  * What is scale
  * In LE lit, how has scale been investigated
  * Elements of scale relevant to animal social systems, animal movement data, landcover data
* Box 1: Types of spatially explicit data and considerations relevant to these e.g. fix rate/grouping with GPS and gambit of the group, etc (table)
* Box 2: Mathematical + language definitions of multilayer networks, metrics and measures of ML networks that are relevant to spatial data
* Simulations
* Discussion/results
* Brief conclusion


---

From a sample of CZ papers:

* Abstract
* Materials and Methods
* Results
* Discussion

and sometimes
* Conservation implications
* Conclusion